Feat: Box 컴포넌트
YAPP-admin/yapp-web pull request #3
Opened 2022-02-02 10:49 UTC by ksmfou98

## 📘 작업 유형

- 신규 기능 추가
- 리펙토링

<br/>

## 📑 작업리스트

> 작업한 목록

- Button component 스타일, props 타입 분리
- Box 컴포넌트 구현

<br />

## 🚧 특이 사항

> PR을 읽을 때 살펴볼 사항

Box 컴포넌트는 사용되는 곳이 좀 다양해서 필수 값들 위주로만 했습니다!   
사용되는 곳이 다양하다 보니 스타일을 미리 예측하기가 좀 그래서, 미디어 쿼리나 그 외 추가 스타일을 주고 싶으면 사용되는 부분에서 `Box`를 상속 받아서 하는 식으로 하시는건 어떠신가욤?

혹시 더 좋은 의견 있으시면 코멘트 부탁드립니다!

ex)  Box에 media 쿼리를 사용할 경우
```javascript
const StyledBox = styled(Box)`
  ${media.desktop} {
      width: 80px
   }
`
```

ex) Box에 margin 값을 주고 싶은 경우
```javascript
const StyledBox = styled(Box)`
  margin: 0 0 10px 0;
`
```

2022-02-02 10:53 UTC, ksmfou98 commented on components/Box.tsx
> +  borderRadius = '20px',
와이어 프레임에서 대부분이 `borderRadius` 가 20px이라 `default`로 설정했습니다!

2022-02-02 10:53 UTC, ksmfou98 commented on components/Box.tsx
> +}
`width`, `height`, `borderRadius` 값이 `100%, 23rem, 30px` 이런식으로 여러 단위가 가능하게   `string` 타입으로 지정했습니다!

2022-02-02 10:53 UTC, ksmfou98 commented on styles/theme.ts
> +
`palette` 객체의 `key` 타입을 사용할 수 있게 `PaletteTypes`를 만들었습니다!

2022-02-02 10:56 UTC, ksmfou98 commented on components/Box.tsx
> +}
`borderRadius`는 `number`로 하는게 나을까요 `string`으로 받는게 나을까요 !?

2022-02-02 14:19 UTC, kyoung-jnn requested changes

2022-02-02 14:19 UTC, kyoung-jnn commented on components/Box.tsx
> +}
음..길이를 받는 부분이
`string` 이면 실수로 `10p`, `100$` 이런식으로 들어갈수도 있을거 같아서
항상 `number` 로 받는게 낫지 않을까요??

`isFixedWidth: boolean`이란 속성을 줘서 해당 값이 `true` 면 항상 width가 100%가 되면 어떨까용

2022-02-02 14:19 UTC, kyoung-jnn commented on components/Button.tsx
> +interface IButtonStyled {
`IButtonStyled` 대신 `IButtonStyle` 어떨까요..? 😳

2022-02-02 14:23 UTC, kyoung-jnn commented
**Box**를 상속 받는 로직 좋은 것 같습니다!

2022-02-03 00:44 UTC, ksmfou98 commented on components/Box.tsx
> +}
오우! 그런 경우를 생각 못했네요 ㅋㅋㅋㅋ 감사합니다 ㄷㄷ!

2022-02-03 00:44 UTC, ksmfou98 commented on components/Button.tsx
> +interface IButtonStyled {
너~무 좋습니다!

2022-02-03 08:31 UTC, kyoung-jnn approved these changes
고생하셨습니다 👏👏👏👏👏

2022-02-03 10:26 UTC, merged