feat: 헤더 컴포넌트 개발
YAPP-admin/yapp-web pull request #4
Opened 2022-02-03 14:23 UTC by ksmfou98

## 📘 작업 유형

- 신규 기능 추가
- 리펙토링

<br/>

## 📑 작업리스트

> 작업한 목록

- 헤더 컴포넌트 개발 (데스크탑)
- Path Enum 생성
- theme type 설정

<br />

## 🚧 특이 사항

> PR을 읽을 때 살펴볼 사항

2022-02-03 14:25 UTC, ksmfou98 commented on constants/breakpoints.ts
> +
사이즈를 css에서 써야 하는 상황들이 있어서 `Breakpoints` 상수로 따로 만들었습니다!

2022-02-03 14:25 UTC, ksmfou98 commented on constants/path.ts
> +
현재 나와있는 라우팅들 enum 으로 상수화 해놨습니다!

2022-02-03 14:25 UTC, ksmfou98 commented on styles/styled.d.ts
> +    lineHeight: LineHeightTypes;
theme type 지정 해놨습니다!

2022-02-04 01:01 UTC, kyoung-jnn requested changes

2022-02-04 01:01 UTC, kyoung-jnn commented on styles/styled.d.ts
> +    lineHeight: LineHeightTypes;
감사합니다~

2022-02-04 07:42 UTC, ksmfou98 commented on components/Header.tsx
> +`;
오우 좋습니다~! 
textStyle을 어떤식으로 사용하는지 몰랐었는데 감사합니다!

2022-02-04 14:48 UTC, kyoung-jnn approved these changes
고생하셨습니다~~~

2022-02-04 14:54 UTC, merged